#!/bin/bash

# output brightness once on startup to get an inital value
bc <<< "scale=2; $(brightnessctl g) / $(brightnessctl m)" | tr -d '.'
while inotifywait -e modify /sys/class/backlight/amdgpu_bl0/brightness &>/dev/null ; do
    bc <<< "scale=2; $(brightnessctl g) / $(brightnessctl m)" | tr -d '.'
done
