#!/bin/sh
workspaces() {

ws1=I
ws2=II
ws3=III
ws4=IV
ws5=V
ws6=VI

# Unoccupied
un="O"
sep="_"

# check if Occupied
o1=$(bspc query -D -d .occupied --names | grep -w "$ws1" )
o2=$(bspc query -D -d .occupied --names | grep -w "$ws2" )
o3=$(bspc query -D -d .occupied --names | grep -w "$ws3" )
o4=$(bspc query -D -d .occupied --names | grep -w "$ws4" )
o5=$(bspc query -D -d .occupied --names | grep -w "$ws5" )
o6=$(bspc query -D -d .occupied --names | grep -w "$ws6" )

# check if Focused
f1=$(bspc query -D -d focused --names | grep -w "$ws1" )
f2=$(bspc query -D -d focused --names | grep -w "$ws2" )
f3=$(bspc query -D -d focused --names | grep -w "$ws3" )
f4=$(bspc query -D -d focused --names | grep -w "$ws4" )
f5=$(bspc query -D -d focused --names | grep -w "$ws5" )
f6=$(bspc query -D -d focused --names | grep -w "$ws6" )

ic_1=""
ic_2=""
ic_3=""
ic_4=""
ic_5=""
ic_6=""

if [ "$f1" ]; then
    ic_1=""
elif [ "$f2" ]; then
    ic_2=""
elif [ "$f3" ]; then
    ic_3=""
elif [ "$f4" ]; then
    ic_4=""
elif [ "$f5" ]; then
    ic_5=""
elif [ "$f6" ]; then
    ic_6=""
fi
echo "(box" \
	    ":class \"works\"" \
        ":orientation \"h\"" \
        ":spacing SPACING" \
        ":space-evenly \"false\"" \
        "(button" \
            ":onclick \"bspc desktop -f $ws1\"" \
            ":class	\"$un$o1$sep$f1\" \"$ic_1\"" \
        ")" \
        "(button" \
            ":onclick \"bspc desktop -f $ws2\"" \
        	":class \"$un$o2$sep$f2\" \"$ic_2\"" \
        ")" \
        "(button" \
            ":onclick \"bspc desktop -f $ws3\"" \
            ":class \"$un$o3$sep$f3\" \"$ic_3\"" \
        ")" \
        "(button" \
            ":onclick \"bspc desktop -f $ws4\"" \
            ":class \"$un$o4$sep$f4\" \"$ic_4\"" \
        ")" \
        "(button" \
            ":onclick \"bspc desktop -f $ws5\"" \
            ":class \"$un$o5$sep$f5\" \"$ic_5\"" \
        ")" \
        "(button" \
            ":onclick \"bspc desktop -f $ws6\"" \
            ":class \"$un$o6$sep$f6\" \"$ic_6\"" \
        ")" \
    ")"

}
workspaces
bspc subscribe desktop node_transfer | while read -r _ ; do
    workspaces
done
