#! /bin/sh

# xrandr
"$HOME"/.config/xrandr/conf.sh &

# sxhkd if it's not running already
pgrep -x sxhkd > /dev/null || sxhkd &

# eww bar if it's not running already
if ! (eww ping &>/dev/null); then
    eww daemon
fi
eww open bar

# lockscreen
xss-lock -- xsecurelock &

# workspaces
INTERNAL_MONITOR="DP-2"
EXTERNAL_MONITOR="HDMI-1"
bspc monitor "$INTERNAL_MONITOR" -d I II III IV
bspc monitor "$EXTERNAL_MONITOR" -d V VI VII VIII

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# Rules
bspc rule -a Signal desktop=^6
bspc rule -a Discord desktop=^6
bspc rule -a spotify desktop=^5
bspc rule -a thunderbird desktop=^4

# Border
bspc config focused_border_color        "#ff79c6"
bspc config normal_border_color         "#44475a"
bspc config active_border_color         "#44475a"

# Notifications
/usr/bin/dunst &
# Wallpaper
nitrogen --restore &
# Picom
picom --experimental-backends &
# Cursor
xsetroot -cursor_name left_ptr &
# automounting
udiskie &
